name: C/C++ CI

on:
    push:
        branches: ["master"]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v3
            - name: change directory
              run: cd /home/ragserver/actions-runner/rathena-server/rathena/rathena
            - name: pause server
              run: sudo./athena-stop stop
            - name: configure
              run: ./configure --enable-packetver=20180620
            - name: make limpa build
              run: make clean
            - name: compila build
              run: make server
            - name: give permissions
              run: sudo chmod a+x login-server && sudo chmod a+x char-server && sudo chmod a+x map-server
            - name: run server
              run: sudo ./athena-start start
